/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO., LTD
 * SPDX-License-Identifier: LicenseRef-Espressif-Modified-MIT
 *
 * See LICENSE file for details.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif  /* __cplusplus */

#define ESP_PLAYER_SERVICE_DEFAULT_PROCESS_PERIOD_MS  20
#define ESP_PLAYER_SERVICE_DEFAULT_PROCESS_BUF_ALIGN  16

#define ESP_PLAYER_SERVICE_DEFAULT_TASK_STACK_SIZE  4096
#define ESP_PLAYER_SERVICE_DEFAULT_TASK_PRIORITY    5
#define ESP_PLAYER_SERVICE_DEFAULT_TASK_CORE_ID     (-1)

#define ESP_PLAYER_SERVICE_DEFAULT_DEFER_TASK_STACK  4096
#define ESP_PLAYER_SERVICE_DEFAULT_DEFER_TASK_PRIO   5
#define ESP_PLAYER_SERVICE_DEFAULT_DEFER_TASK_CORE   (-1)

#define ESP_PLAYER_SERVICE_DEFAULT_PLAYER_TASK_STACK          5120
#define ESP_PLAYER_SERVICE_DEFAULT_PLAYER_TASK_PRIO           5
#define ESP_PLAYER_SERVICE_DEFAULT_PLAYER_EXTRACTOR_CORE      0
#define ESP_PLAYER_SERVICE_DEFAULT_PLAYER_AUDIO_DECODER_CORE  1
#define ESP_PLAYER_SERVICE_DEFAULT_PLAYER_AUDIO_RENDER_CORE   0
#define ESP_PLAYER_SERVICE_DEFAULT_PLAYER_VIDEO_DECODER_CORE  0
#define ESP_PLAYER_SERVICE_DEFAULT_PLAYER_VIDEO_RENDER_CORE   0

#define ESP_PLAYER_SERVICE_DEFAULT_RENDER_TASK_STACK  6144
#define ESP_PLAYER_SERVICE_DEFAULT_RENDER_TASK_PRIO   10
#define ESP_PLAYER_SERVICE_DEFAULT_RENDER_TASK_CORE   1

#define ESP_PLAYER_SERVICE_FEED_TIMEOUT_MS           1000
#define ESP_PLAYER_SERVICE_ACQUIRE_FRAME_TIMEOUT_MS  20
#define ESP_PLAYER_SERVICE_TASK_JOIN_POLL_MS         10
#define ESP_PLAYER_SERVICE_TASK_JOIN_WARN_EVERY      150

#define ESP_PLAYER_SERVICE_FEED_TRACK_AUDIO  0
#define ESP_PLAYER_SERVICE_FEED_TRACK_VIDEO  1
#define ESP_PLAYER_SERVICE_FEED_TRACK_MAX    2

#ifdef __cplusplus
}
#endif  /* __cplusplus */
