include:
  - '.gitlab/ci/common.yml'
  - '.gitlab/ci/rules.yml'
  - '.gitlab/ci/docs.yml'
  - '.gitlab/ci/trigger.yml'
  - '.gitlab/ci/pre-check.yml'

stages:
  - pre_check
  - trigger_build
  - test_deploy
  - deploy

before_script:
  - source $PROJECT_ROOT/tools/ci/utils.sh
  - before_script

push_to_github:
  stage: deploy
  extends:
    - .rules:build:push-to-github
  needs:
    - job: trigger-dynamic-pipelines
  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
  before_script:
    - echo "skip default before_script"
  script:
    - source $PROJECT_ROOT/tools/ci/utils.sh
    - add_github_ssh_keys
    - git fetch --unshallow
    - git remote remove github &>/dev/null || true
    - git remote add github git@github.com:espressif/esp-adf.git
    - tools/ci/push_to_github.sh
