repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1 #latest release version
    hooks:
      - id: codespell
        args: [--config=.codespellrc]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: double-quote-string-fixer
      - id: no-commit-to-branch
        name: Do not use more than one slash in the branch name
        args: ['--pattern', '^[^/]*/[^/]*/']
      - id: no-commit-to-branch
        name: Do not use uppercase letters in the branch name
        args: ['--pattern', '^[^A-Z]*[A-Z]']
      - id: trailing-whitespace
        types_or: [c, c++]

  - repo: https://github.com/COFFER-S/check-format-tool
    rev: v1.1.3
    hooks:
      - id: code-style
        args: ['--local', '-f', 'code-style']
        types_or: [c, c++]
      - id: branch-name
        args: ['branch-name']
      - id: commit-message
        args: ['--ci', 'commit-message']
