PROJECT_NAME := esp_dueros
EXTRA_COMPONENT_DIRS += $(ADF_PATH)/../esp-adf-libs-source-dev/
EXTRA_COMPONENT_DIRS += $(ADF_PATH)/../esp-adf-libs-source-dev/esp_codec
EXTRA_COMPONENT_DIRS += $(ADF_PATH)/../esp-adf-libs-source-dev/esp_codec/esp-share
EXTRA_COMPONENT_DIRS += $(ADF_PATH)/../esp-adf-libs-source-dev/esp_codec/esp-aac
include $(ADF_PATH)/project.mk
