# type: ignore
# -*- coding: utf-8 -*-
#
# Simplified Chinese Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.
# Importing conf_common adds all the non-language-specific
# parts to this conf module
try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    sys.path.insert(0, os.path.abspath('..'))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year

# General information about the project.
project = u'乐鑫高级开发框架指南'
copyright = u'2017 - {}, 乐鑫信息科技（上海）股份有限公司'.format(current_year)

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'zh_CN'

# Name of the downloadable HTML archive produced by the
# `esp_docs.esp_extensions.add_html_zip` extension. The file is placed inside
# the built `html/` directory; the sphinx_idf_theme version selector picks it
# up as the "Download HTML" link.
html_zip = f'esp-adf-{language}-{release}'  # noqa: F405
