#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := element_wav_amr_sdcard

ifeq ($(ADF_PATH),)
  $(error Please specify ADF_PATH)
endif

include $(ADF_PATH)/project.mk
